repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python
      args: [--line-length=120]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    - id: flake8
      args: [--max-line-length=120]
-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest tests
        language: system
        types: [python]
        stages: [push]